"""Custom SQLAlchemy column types.

Two problems this module exists to solve:

``UTCDateTime``
    SQLite has no timezone-aware datetime type. ``DateTime(timezone=True)``
    therefore hands back a *naive* datetime, and comparing that to an aware
    one raises ``TypeError`` somewhere far away from the cause. This type
    normalises on the way in and re-attaches UTC on the way out, so the rest
    of the application only ever sees aware datetimes.

``str_enum``
    SQLAlchemy stores an ``Enum`` by member *name* by default. These enums are
    :class:`~enum.StrEnum` whose value is already the readable form, so the
    column is configured to persist the value instead.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import JSON, Dialect, TypeDecorator
from sqlalchemy import Enum as SAEnum
from sqlalchemy.types import DateTime

#: Longest enum value across the application, with room to grow.
_ENUM_LENGTH = 40


class UTCDateTime(TypeDecorator[datetime]):
    """A ``DateTime`` column that is always timezone-aware and always UTC.

    ``impl`` is the ``DateTime`` *class* rather than an instance so that
    ``UTCDateTime(timezone=True)`` constructs correctly - which is the form
    Alembic writes into an autogenerated migration.
    """

    impl = DateTime
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        """Normalise an inbound datetime to UTC before it is written."""
        if value is None:
            return None
        if value.tzinfo is None:
            # A naive value reaching the database is a bug upstream, but
            # assuming UTC is strictly better than writing an ambiguous row.
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)

    def process_result_value(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        """Re-attach UTC to a value the driver returned naive."""
        if value is None:
            return None
        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)


def str_enum(enum_cls: type[StrEnum]) -> SAEnum:
    """Return an ``Enum`` column type that persists the member *value*.

    Args:
        enum_cls: The :class:`~enum.StrEnum` subclass to store.

    Returns:
        A configured SQLAlchemy ``Enum`` using a ``VARCHAR`` with a CHECK
        constraint rather than a database-native enum, which keeps SQLite and
        PostgreSQL behaving identically.
    """
    return SAEnum(
        enum_cls,
        native_enum=False,
        validate_strings=True,
        values_callable=lambda members: [member.value for member in members],
        length=_ENUM_LENGTH,
        name=f"{enum_cls.__name__.lower()}_enum",
    )


#: Type used for the handful of genuinely schemaless columns (tag lists,
#: score breakdowns, recurrence day sets). Anything queried by value gets a
#: real column instead.
JSONColumn: Any = JSON
