"""initial schema

Revision ID: fad5d19301b8
Revises: 
Create Date: 2026-09-10 14:32:14.143813
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Autogenerated columns may reference the project's custom column types.
import app.database.types  # noqa: F401

revision: str = 'fad5d19301b8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings')),
    sa.UniqueConstraint('key', name='uq_app_settings_key')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=False)

    op.create_table('user_profile',
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'UNSPECIFIED', name='sex_enum', native_enum=False, length=40), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', 'EXTRA_ACTIVE', name='activitylevel_enum', native_enum=False, length=40), nullable=False),
    sa.Column('bmr_formula', sa.Enum('MIFFLIN_ST_JEOR', 'HARRIS_BENEDICT', 'KATCH_MCARDLE', name='bmrformula_enum', native_enum=False, length=40), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('week_start', sa.Integer(), nullable=False),
    sa.Column('target_sleep_minutes', sa.Integer(), nullable=False),
    sa.Column('target_study_minutes', sa.Integer(), nullable=False),
    sa.Column('target_coding_minutes', sa.Integer(), nullable=False),
    sa.Column('target_teaching_minutes', sa.Integer(), nullable=False),
    sa.Column('target_exercise_minutes', sa.Integer(), nullable=False),
    sa.Column('target_bedtime', sa.Time(), nullable=True),
    sa.Column('target_wake_time', sa.Time(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('height_cm IS NULL OR height_cm BETWEEN 50 AND 280', name=op.f('ck_user_profile_height_range')),
    sa.CheckConstraint('week_start BETWEEN 0 AND 6', name=op.f('ck_user_profile_week_start_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_created_at'), ['created_at'], unique=False)

    op.create_table('body_measurement',
    sa.Column('measured_on', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_percent', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('body_fat_percent IS NULL OR body_fat_percent BETWEEN 1 AND 70', name=op.f('ck_body_measurement_body_fat_range')),
    sa.CheckConstraint('weight_kg > 0 AND weight_kg < 500', name=op.f('ck_body_measurement_weight_range')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_body_measurement_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_measurement')),
    sa.UniqueConstraint('user_id', 'measured_on', name='uq_body_measurement_user_date')
    )
    with op.batch_alter_table('body_measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_measurement_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_measurement_measured_on'), ['measured_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_measurement_user_id'), ['user_id'], unique=False)

    op.create_table('category',
    sa.Column('kind', sa.Enum('TASK', 'HABIT', 'ACTIVITY', 'TIME', name='categorykind_enum', native_enum=False, length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('is_productive', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_category_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('user_id', 'kind', 'name', name='uq_category_user_kind_name')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_user_id'), ['user_id'], unique=False)

    op.create_table('daily_log',
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('main_goal', sa.String(length=255), nullable=True),
    sa.Column('priorities', sa.JSON(), nullable=True),
    sa.Column('planned_study_minutes', sa.Integer(), nullable=True),
    sa.Column('planned_exercise_minutes', sa.Integer(), nullable=True),
    sa.Column('morning_energy', sa.Integer(), nullable=True),
    sa.Column('checkin_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('day_rating', sa.Integer(), nullable=True),
    sa.Column('what_went_wrong', sa.Text(), nullable=True),
    sa.Column('improve_tomorrow', sa.Text(), nullable=True),
    sa.Column('review_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('productivity_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('score_computed_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('day_rating IS NULL OR day_rating BETWEEN 1 AND 10', name=op.f('ck_daily_log_day_rating_range')),
    sa.CheckConstraint('planned_exercise_minutes IS NULL OR planned_exercise_minutes >= 0', name=op.f('ck_daily_log_planned_exercise_non_negative')),
    sa.CheckConstraint('planned_study_minutes IS NULL OR planned_study_minutes >= 0', name=op.f('ck_daily_log_planned_study_non_negative')),
    sa.CheckConstraint('productivity_score IS NULL OR productivity_score BETWEEN 0 AND 100', name=op.f('ck_daily_log_score_range')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_daily_log_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_log')),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_daily_log_user_date')
    )
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_log_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_log_productivity_score'), ['productivity_score'], unique=False)
        batch_op.create_index('ix_daily_log_user_date', ['user_id', 'log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_log_user_id'), ['user_id'], unique=False)

    op.create_table('goal',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('PERSONAL', 'FITNESS', 'LEARNING', 'CAREER', 'FINANCIAL', 'PROJECT', 'HEALTH', 'OTHER', name='goalcategory_enum', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'ABANDONED', name='goalstatus_enum', native_enum=False, length=40), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority_enum', native_enum=False, length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('completed_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('progress_percent BETWEEN 0 AND 100', name=op.f('ck_goal_progress_range')),
    sa.CheckConstraint('target_date IS NULL OR start_date IS NULL OR target_date >= start_date', name=op.f('ck_goal_date_order')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_goal_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal'))
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_goal_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index('ix_goal_user_target_date', ['user_id', 'target_date'], unique=False)

    op.create_table('journal_entry',
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.Integer(), nullable=True),
    sa.Column('focus', sa.Integer(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('accomplishments', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('gratitude', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('energy IS NULL OR energy BETWEEN 1 AND 10', name=op.f('ck_journal_entry_energy_range')),
    sa.CheckConstraint('focus IS NULL OR focus BETWEEN 1 AND 10', name=op.f('ck_journal_entry_focus_range')),
    sa.CheckConstraint('mood IS NULL OR mood BETWEEN 1 AND 10', name=op.f('ck_journal_entry_mood_range')),
    sa.CheckConstraint('motivation IS NULL OR motivation BETWEEN 1 AND 10', name=op.f('ck_journal_entry_motivation_range')),
    sa.CheckConstraint('stress IS NULL OR stress BETWEEN 1 AND 10', name=op.f('ck_journal_entry_stress_range')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_journal_entry_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entry')),
    sa.UniqueConstraint('user_id', 'entry_date', name='uq_journal_entry_user_date')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index('ix_journal_entry_user_date', ['user_id', 'entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_user_id'), ['user_id'], unique=False)

    op.create_table('sleep_record',
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('bedtime_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sleep_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('wake_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('interruptions', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 1440', name=op.f('ck_sleep_record_duration_plausible')),
    sa.CheckConstraint('interruptions >= 0', name=op.f('ck_sleep_record_interruptions_non_negative')),
    sa.CheckConstraint('quality IS NULL OR quality BETWEEN 1 AND 10', name=op.f('ck_sleep_record_quality_range')),
    sa.CheckConstraint('wake_at > sleep_at', name=op.f('ck_sleep_record_wake_after_sleep')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_sleep_record_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sleep_record')),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_sleep_record_user_date')
    )
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_record_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_record_log_date'), ['log_date'], unique=False)
        batch_op.create_index('ix_sleep_record_user_date', ['user_id', 'log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sleep_record_user_id'), ['user_id'], unique=False)

    op.create_table('weekly_goal',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('metric', sa.Enum('STUDY_MINUTES', 'CODING_MINUTES', 'TEACHING_MINUTES', 'EXERCISE_MINUTES', 'SLEEP_MINUTES', 'TASKS_COMPLETED', 'HABIT_COMPLETIONS', name='weeklymetric_enum', native_enum=False, length=40), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('target_value > 0', name=op.f('ck_weekly_goal_target_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_weekly_goal_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_goal')),
    sa.UniqueConstraint('user_id', 'week_start', 'metric', name='uq_weekly_goal_user_week_metric')
    )
    with op.batch_alter_table('weekly_goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_goal_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_goal_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_weekly_goal_user_week', ['user_id', 'week_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_goal_week_start'), ['week_start'], unique=False)

    op.create_table('activity',
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('started_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('intensity', sa.Enum('LOW', 'MODERATE', 'HIGH', name='activityintensity_enum', native_enum=False, length=40), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('calories IS NULL OR calories >= 0', name=op.f('ck_activity_calories_non_negative')),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_activity_duration_positive')),
    sa.CheckConstraint('ended_at IS NULL OR started_at IS NULL OR ended_at > started_at', name=op.f('ck_activity_end_after_start')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_activity_category_id_category'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_activity_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_date'), ['log_date'], unique=False)
        batch_op.create_index('ix_activity_user_category_date', ['user_id', 'category_id', 'log_date'], unique=False)
        batch_op.create_index('ix_activity_user_date', ['user_id', 'log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_user_id'), ['user_id'], unique=False)

    op.create_table('goal_milestone',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], name=op.f('fk_goal_milestone_goal_id_goal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_milestone'))
    )
    with op.batch_alter_table('goal_milestone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_milestone_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_milestone_goal_id'), ['goal_id'], unique=False)
        batch_op.create_index('ix_goal_milestone_goal_order', ['goal_id', 'sort_order'], unique=False)

    op.create_table('habit',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('habit_type', sa.Enum('BOOLEAN', 'COUNT', 'DURATION', 'QUANTITY', 'TIME', name='habittype_enum', native_enum=False, length=40), nullable=False),
    sa.Column('direction', sa.Enum('AT_LEAST', 'AT_MOST', 'BEFORE', 'AFTER', name='habitdirection_enum', native_enum=False, length=40), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKDAYS', 'WEEKENDS', 'SPECIFIC_DAYS', 'TIMES_PER_WEEK', name='habitfrequency_enum', native_enum=False, length=40), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('min_target', sa.Float(), nullable=True),
    sa.Column('ideal_target', sa.Float(), nullable=True),
    sa.Column('target_time', sa.Time(), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=True),
    sa.Column('specific_days', sa.JSON(), nullable=True),
    sa.Column('rest_days', sa.JSON(), nullable=True),
    sa.Column('times_per_week', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name=op.f('ck_habit_date_order')),
    sa.CheckConstraint('target_value IS NULL OR target_value >= 0', name=op.f('ck_habit_target_non_negative')),
    sa.CheckConstraint('times_per_week IS NULL OR times_per_week BETWEEN 1 AND 7', name=op.f('ck_habit_times_per_week_range')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_habit_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_habit_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit')),
    sa.UniqueConstraint('user_id', 'name', name='uq_habit_user_name')
    )
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_start_date'), ['start_date'], unique=False)
        batch_op.create_index('ix_habit_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_user_id'), ['user_id'], unique=False)

    op.create_table('task',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority_enum', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'CANCELLED', name='taskstatus_enum', native_enum=False, length=40), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('recurrence', sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='recurrencerule_enum', native_enum=False, length=40), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=False),
    sa.Column('recurrence_days', sa.JSON(), nullable=True),
    sa.Column('recurrence_until', sa.Date(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('actual_minutes IS NULL OR actual_minutes >= 0', name=op.f('ck_task_actual_non_negative')),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes >= 0', name=op.f('ck_task_estimated_non_negative')),
    sa.CheckConstraint('recurrence_interval >= 1', name=op.f('ck_task_recurrence_interval_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_task_category_id_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task.id'], name=op.f('fk_task_parent_task_id_task'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_task_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)
        batch_op.create_index('ix_task_user_completed_at', ['user_id', 'completed_at'], unique=False)
        batch_op.create_index('ix_task_user_due', ['user_id', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_task_user_status_due', ['user_id', 'status', 'due_date'], unique=False)

    op.create_table('time_entry',
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('started_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_time_entry_duration_positive')),
    sa.CheckConstraint('ended_at IS NULL OR started_at IS NULL OR ended_at > started_at', name=op.f('ck_time_entry_end_after_start')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_time_entry_category_id_category'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_time_entry_user_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entry'))
    )
    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entry_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entry_log_date'), ['log_date'], unique=False)
        batch_op.create_index('ix_time_entry_user_category_date', ['user_id', 'category_id', 'log_date'], unique=False)
        batch_op.create_index('ix_time_entry_user_date', ['user_id', 'log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entry_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_time_entry_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('habit_log',
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_time', sa.Time(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('value IS NULL OR value >= 0', name=op.f('ck_habit_log_value_non_negative')),
    sa.ForeignKeyConstraint(['habit_id'], ['habit.id'], name=op.f('fk_habit_log_habit_id_habit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_log')),
    sa.UniqueConstraint('habit_id', 'log_date', name='uq_habit_log_habit_date')
    )
    with op.batch_alter_table('habit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_habit_log_date_completed', ['log_date', 'completed'], unique=False)
        batch_op.create_index('ix_habit_log_habit_date', ['habit_id', 'log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_log_habit_id'), ['habit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_log_log_date'), ['log_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_log_log_date'))
        batch_op.drop_index(batch_op.f('ix_habit_log_habit_id'))
        batch_op.drop_index('ix_habit_log_habit_date')
        batch_op.drop_index('ix_habit_log_date_completed')
        batch_op.drop_index(batch_op.f('ix_habit_log_created_at'))

    op.drop_table('habit_log')
    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_time_entry_user_started')
        batch_op.drop_index(batch_op.f('ix_time_entry_user_id'))
        batch_op.drop_index('ix_time_entry_user_date')
        batch_op.drop_index('ix_time_entry_user_category_date')
        batch_op.drop_index(batch_op.f('ix_time_entry_log_date'))
        batch_op.drop_index(batch_op.f('ix_time_entry_created_at'))
        batch_op.drop_index(batch_op.f('ix_time_entry_category_id'))

    op.drop_table('time_entry')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('ix_task_user_status_due')
        batch_op.drop_index(batch_op.f('ix_task_user_id'))
        batch_op.drop_index('ix_task_user_due')
        batch_op.drop_index('ix_task_user_completed_at')
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_priority'))
        batch_op.drop_index(batch_op.f('ix_task_parent_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_created_at'))
        batch_op.drop_index(batch_op.f('ix_task_category_id'))

    op.drop_table('task')
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_user_id'))
        batch_op.drop_index('ix_habit_user_active')
        batch_op.drop_index(batch_op.f('ix_habit_start_date'))
        batch_op.drop_index(batch_op.f('ix_habit_created_at'))
        batch_op.drop_index(batch_op.f('ix_habit_category_id'))

    op.drop_table('habit')
    with op.batch_alter_table('goal_milestone', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_milestone_goal_order')
        batch_op.drop_index(batch_op.f('ix_goal_milestone_goal_id'))
        batch_op.drop_index(batch_op.f('ix_goal_milestone_created_at'))

    op.drop_table('goal_milestone')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_user_id'))
        batch_op.drop_index('ix_activity_user_date')
        batch_op.drop_index('ix_activity_user_category_date')
        batch_op.drop_index(batch_op.f('ix_activity_log_date'))
        batch_op.drop_index(batch_op.f('ix_activity_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_category_id'))

    op.drop_table('activity')
    with op.batch_alter_table('weekly_goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_goal_week_start'))
        batch_op.drop_index('ix_weekly_goal_user_week')
        batch_op.drop_index(batch_op.f('ix_weekly_goal_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_goal_created_at'))

    op.drop_table('weekly_goal')
    with op.batch_alter_table('sleep_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_record_user_id'))
        batch_op.drop_index('ix_sleep_record_user_date')
        batch_op.drop_index(batch_op.f('ix_sleep_record_log_date'))
        batch_op.drop_index(batch_op.f('ix_sleep_record_created_at'))

    op.drop_table('sleep_record')
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_user_id'))
        batch_op.drop_index('ix_journal_entry_user_date')
        batch_op.drop_index(batch_op.f('ix_journal_entry_entry_date'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_created_at'))

    op.drop_table('journal_entry')
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_user_target_date')
        batch_op.drop_index('ix_goal_user_status')
        batch_op.drop_index(batch_op.f('ix_goal_user_id'))
        batch_op.drop_index(batch_op.f('ix_goal_created_at'))
        batch_op.drop_index(batch_op.f('ix_goal_category'))

    op.drop_table('goal')
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_log_user_id'))
        batch_op.drop_index('ix_daily_log_user_date')
        batch_op.drop_index(batch_op.f('ix_daily_log_productivity_score'))
        batch_op.drop_index(batch_op.f('ix_daily_log_log_date'))
        batch_op.drop_index(batch_op.f('ix_daily_log_created_at'))

    op.drop_table('daily_log')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_user_id'))
        batch_op.drop_index(batch_op.f('ix_category_kind'))
        batch_op.drop_index(batch_op.f('ix_category_is_active'))
        batch_op.drop_index(batch_op.f('ix_category_created_at'))

    op.drop_table('category')
    with op.batch_alter_table('body_measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_measurement_user_id'))
        batch_op.drop_index(batch_op.f('ix_body_measurement_measured_on'))
        batch_op.drop_index(batch_op.f('ix_body_measurement_created_at'))

    op.drop_table('body_measurement')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_created_at'))

    op.drop_table('user_profile')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.drop_index(batch_op.f('ix_app_settings_created_at'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
