"""Pydantic schemas - the contract between the UI and the service layer."""

from app.schemas.activity import (
    ActivityInput,
    ActivityRead,
    AllocationRead,
    AllocationSliceRead,
    CategoryCreate,
    CategoryRead,
    CategoryUpdate,
    TimeEntryFilter,
    TimeEntryInput,
    TimeEntryRead,
)
from app.schemas.analytics import (
    BucketRead,
    ComparisonRead,
    HabitPerformanceRead,
    HeatmapPoint,
    HeatmapRead,
    InsightRead,
    MonthlyReview,
    PeriodSummary,
    RecommendationRead,
    SeriesPoint,
    WeeklyReview,
)
from app.schemas.common import DateRange, Page, Pagination, ReadSchema, Schema
from app.schemas.dashboard import (
    DailySummary,
    DashboardView,
    HabitCounts,
    ProductivityScoreRead,
    ScoreComponentRead,
    TaskCounts,
    TimelineItem,
)
from app.schemas.goal import (
    GoalCreate,
    GoalPaceRead,
    GoalRead,
    GoalUpdate,
    MilestoneInput,
    MilestoneRead,
    WeeklyGoalInput,
    WeeklyGoalRead,
)
from app.schemas.habit import (
    HabitCreate,
    HabitLogInput,
    HabitLogRead,
    HabitRead,
    HabitStreakRead,
    HabitTodayRead,
    HabitUpdate,
)
from app.schemas.health import (
    BodyMeasurementInput,
    BodyMeasurementRead,
    HealthSnapshot,
    ProfileRead,
    ProfileUpdate,
    WeightTrendRead,
)
from app.schemas.journal import (
    DailyLogRead,
    EveningReview,
    JournalInput,
    JournalRead,
    MorningCheckIn,
)
from app.schemas.sleep import SleepInput, SleepRead, SleepStatsRead
from app.schemas.task import TaskCreate, TaskFilter, TaskRead, TaskUpdate

__all__ = [
    "ActivityInput",
    "ActivityRead",
    "AllocationRead",
    "AllocationSliceRead",
    "BodyMeasurementInput",
    "BodyMeasurementRead",
    "BucketRead",
    "CategoryCreate",
    "CategoryRead",
    "CategoryUpdate",
    "ComparisonRead",
    "DailyLogRead",
    "DailySummary",
    "DashboardView",
    "DateRange",
    "EveningReview",
    "GoalCreate",
    "GoalPaceRead",
    "GoalRead",
    "GoalUpdate",
    "HabitCounts",
    "HabitCreate",
    "HabitLogInput",
    "HabitLogRead",
    "HabitPerformanceRead",
    "HabitRead",
    "HabitStreakRead",
    "HabitTodayRead",
    "HabitUpdate",
    "HealthSnapshot",
    "HeatmapPoint",
    "HeatmapRead",
    "InsightRead",
    "JournalInput",
    "JournalRead",
    "MilestoneInput",
    "MilestoneRead",
    "MonthlyReview",
    "MorningCheckIn",
    "Page",
    "Pagination",
    "PeriodSummary",
    "ProductivityScoreRead",
    "ProfileRead",
    "ProfileUpdate",
    "ReadSchema",
    "RecommendationRead",
    "Schema",
    "ScoreComponentRead",
    "SeriesPoint",
    "SleepInput",
    "SleepRead",
    "SleepStatsRead",
    "TaskCounts",
    "TaskCreate",
    "TaskFilter",
    "TaskRead",
    "TaskUpdate",
    "TimeEntryFilter",
    "TimeEntryInput",
    "TimeEntryRead",
    "TimelineItem",
    "WeeklyGoalInput",
    "WeeklyGoalRead",
    "WeeklyReview",
    "WeightTrendRead",
]
